[package]
name = "toolbelt"
version = "0.1.0"
description = "Toolbelt – developer utilities"
authors = ["akinozgen"]
edition = "2021"

[lib]
name = "toolbelt_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri            = { version = "2", features = ["tray-icon"] }
tauri-plugin-fs  = "2"
tauri-plugin-os  = "2"
tauri-plugin-store = "2"
serde            = { version = "1", features = ["derive"] }
serde_json       = "1"

[target.'cfg(target_os = "windows")'.dependencies]
window-vibrancy = "0.5"

[target.'cfg(target_os = "macos")'.dependencies]
window-vibrancy = "0.5"

[profile.release]
panic   = "abort"
codegen-units = 1
lto     = true
opt-level = "s"
strip   = true
